# -*- coding: utf-8 -*-

from pyglet.window import key, mouse

CONFIRM_BUTTON = [key.ENTER, key.Z]
CONFIRM = "CONFIRM"
CANCEL_BUTTON = [key.X,]
CANCEL = "CANCEL"
LEFT_MOUSE_BUTTON = [mouse.LEFT,]
LEFT_MOUSE = "LEFT_MOUSE"
RIGHT_MOUSE_BUTTON = [mouse.RIGHT,]
RIGHT_MOUSE = "RIGHT_MOUSE"
MOVE_UP_BUTTON = [key.W, key.UP]
MOVE_UP = "MOVE_UP"
MOVE_DOWN_BUTTON = [key.S, key.DOWN]
MOVE_DOWN = "MOVE_DOWN"
MOVE_RIGHT_BUTTON = [key.D, key.RIGHT]
MOVE_RIGHT = "MOVE_RIGHT"
MOVE_LEFT_BUTTON = [key.A, key.LEFT]
MOVE_LEFT = "MOVE_LEFT"
TAKE_SCREENSHOT_BUTTON = [key.P]
TAKE_SCREENSHOT = "TAKE_SCREENSHOT"
CAPTURE_ANIMATION_BUTTON = [key.Y]
CAPTURE_ANIMATION = "CAPTURE_ANIMATION"

KEY_BINDS = {CONFIRM:CONFIRM_BUTTON, CANCEL:CANCEL_BUTTON,
            LEFT_MOUSE:LEFT_MOUSE_BUTTON, RIGHT_MOUSE:RIGHT_MOUSE_BUTTON, MOVE_UP:MOVE_UP_BUTTON,
            MOVE_DOWN:MOVE_DOWN_BUTTON, MOVE_RIGHT:MOVE_RIGHT_BUTTON, MOVE_LEFT:MOVE_LEFT_BUTTON,
            TAKE_SCREENSHOT:TAKE_SCREENSHOT_BUTTON, CAPTURE_ANIMATION:CAPTURE_ANIMATION_BUTTON}
