# -*- coding: utf-8 -*-

from kaiengine.gconfig.paths import *

#extensions

MAP_EXTENSION = ".map"


#code
MAP_DIR = "maps"


#graphics
MAP_TILE_GRAPHICS_FOLDER = "maptiles"
MISC_GRAPHICS_DIR = "misc"
CHAR_GRAPHICS_DIR = "char"
EFFECTS_GRAPHICS_DIR = "effects"
UI_GRAPHICS_DIR = "ui"
BG_GRAPHICS_DIR = "bgs"


#code
MAP_FULL_PATH = [RESOURCE_PATH, CODE_PATH, MAP_DIR]


#graphics
MAP_TILE_GRAPHICS_FULL_PATH = [RESOURCE_PATH, GRAPHICS_PATH, MAP_TILE_GRAPHICS_FOLDER]
MISC_GRAPHICS_FULL_PATH = [RESOURCE_PATH, GRAPHICS_PATH, MISC_GRAPHICS_DIR]
CHAR_GRAPHICS_FULL_PATH = [RESOURCE_PATH, GRAPHICS_PATH, CHAR_GRAPHICS_DIR]
EFFECTS_GRAPHICS_FULL_PATH = [RESOURCE_PATH, GRAPHICS_PATH, EFFECTS_GRAPHICS_DIR]
UI_GRAPHICS_FULL_PATH = [RESOURCE_PATH, GRAPHICS_PATH, UI_GRAPHICS_DIR]
BG_GRAPHICS_FULL_PATH = [RESOURCE_PATH, GRAPHICS_PATH, BG_GRAPHICS_DIR]
